// Mocks generated by Mockito 5.4.6 from annotations
// in namma_wallet/test/api_check_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i3;

import 'package:intl/locale.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pkpass/pkpass.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePassMetadata_0 extends _i1.SmartFake implements _i2.PassMetadata {
  _FakePassMetadata_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PassFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockPassFile extends _i1.Mock implements _i2.PassFile {
  MockPassFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PassMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakePassMetadata_0(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.PassMetadata);

  @override
  _i3.Uint8List? getBackground({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getBackground, [], {
              #locale: locale,
              #scale: scale,
            }),
          )
          as _i3.Uint8List?);

  @override
  _i3.Uint8List? getFooter({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getFooter, [], {#locale: locale, #scale: scale}),
          )
          as _i3.Uint8List?);

  @override
  _i3.Uint8List? getIcon({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getIcon, [], {#locale: locale, #scale: scale}),
          )
          as _i3.Uint8List?);

  @override
  _i3.Uint8List? getLogo({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getLogo, [], {#locale: locale, #scale: scale}),
          )
          as _i3.Uint8List?);

  @override
  _i3.Uint8List? getStrip({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getStrip, [], {#locale: locale, #scale: scale}),
          )
          as _i3.Uint8List?);

  @override
  _i3.Uint8List? getThumbnail({_i4.Locale? locale, int? scale = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getThumbnail, [], {
              #locale: locale,
              #scale: scale,
            }),
          )
          as _i3.Uint8List?);
}
