class StationRegistry {
  StationRegistry._();

  static const Map<String, String> _stations = {
    'ABR': 'Abu Road',
    'ADB': 'Adilabad',
    'AD': 'Adoni',
    'ADRA': 'Adra',
    'AGTL': 'Agartala',
    'AF': 'Agra Fort',
    'AGC': 'Agra Cantt.',
    'ANG': 'Ahmadnagar',
    'ADI': 'Ahmedabad',
    'AII': 'Ajmer',
    'AJNI': 'Ajni',
    'AK': 'Akola',
    'ALJN': 'Aligarh',
    'APDJ': 'Alipurduar Junction',
    'ALD': 'Allahabad',
    'ALLP': 'Alappuzha',
    'LWR': 'Alnawar Junction',
    'AWY': 'Aluva',
    'AWR': 'Alwar',
    'AN': 'Amalner',
    'AADR': 'Amb Andavra',
    'UMB': 'Ambala Cantt.',
    'ABKP': 'Ambikapur',
    'AMLA': 'Amla',
    'ASR': 'Amritsar',
    'AKP': 'Anakapalle',
    'ANND': 'Anand',
    'ANDN': 'Anand Nagar',
    'ANVT': 'Anand Vihar Terminus',
    'ATP': 'Anantapur',
    'ANGL': 'Angul',
    'ANV': 'Annavaram',
    'APR': 'Anuppur',
    'ARA': 'Ara',
    'AJJ': 'Arakkonam',
    'ASK': 'Arsikere',
    'ASN': 'Asansol',
    'ARJ': 'Aunrihar',
    'AWB': 'Aurangabad',
    'AY': 'Ayodhya',
    'AMH': 'Azamgarh',
    'AZ': 'Azimganj Junction',
    'BPB': 'Badarpur',
    'BD': 'Badnera Junction',
    'BGK': 'Bagalkot',
    'BPM': 'Baghpat Road',
    'BDME': 'Baidyanathdham',
    'BKP': 'Bakthiyarpur',
    'BLS': 'Balasore',
    'BTC': 'Balaghat',
    'BLGR': 'Balangir',
    'BALU': 'Balugaon',
    'BLGT': 'Balurghat',
    'BPQ': 'Balharshah',
    'BUI': 'Ballia',
    'BNQ': 'Banarhat',
    'BNDA': 'Banda Junction',
    'BDC': 'Bandel Junction',
    'BKI': 'Bandikui Junction',
    'BDTS': 'Bandra Terminus',
    'SBC': 'Bangalore City',
    'BNC': 'Bangalore Cantt.',
    'BWT': 'Bangarapet',
    'BGY': 'Bangriposi',
    'BQA': 'Bankura',
    'BNKI': 'Banmankhi',
    'BPP': 'Bapatla',
    'BBK': 'Barabanki Junction',
    'BBN': 'Barabil',
    'BAZ': 'Baran',
    'BJU': 'Barauni Junction',
    'BTU': 'Baraut',
    'BRPL': 'Barapalli',
    'BWN': 'Barddhaman Junction',
    'BE': 'Bareilly',
    'BRGA': 'Bargarh Road',
    'BNY': 'Barhni',
    'BRKA': 'Barkakana',
    'BME': 'Barmer',
    'BOF': 'Barog',
    'BOE': 'Barsoi',
    'BRWD': 'Barwadih',
    'BSX': 'Basar',
    'BST': 'Basti',
    'BTI': 'Bathinda Junction',
    'BXN': 'Bayana',
    'BEAS': 'Beas',
    'BER': 'Beawar',
    'BAP': 'Belapur',
    'BGM': 'Belgaum',
    'BAY': 'Bellary Junction',
    'BTH': 'Bettiah',
    'BZU': 'Betul',
    'BOY': 'Bhadohi',
    'BHC': 'Bhadrak',
    'BGP': 'Bhagalpur',
    'BGKI': 'Bhagat Ki Kothi',
    'BTE': 'Bharatpur',
    'BH': 'Bharuch',
    'BYT': 'Bhatapara',
    'BTJL': 'Bhatkal',
    'BTT': 'Bhatni',
    'BVC': 'Bhavnagar Terminus',
    'BWPI': 'Bhawanipatna',
    'BHL': 'Bhilwara',
    'BVRM': 'Bhimavaram Junction',
    'BVRT': 'Bhimavaram Town',
    'BIX': 'Bhind',
    'BNW': 'Bhiwani',
    'BPL': 'Bhopal',
    'BBS': 'Bhubaneswar',
    'BHUJ': 'Bhuj',
    'BSL': 'Bhusaval',
    'BJP': 'Bijapur',
    'BJO': 'Bijnor',
    'BKN': 'Bikaner',
    'BSP': 'Bilaspur Junction',
    'BINA': 'Bina',
    'BNV': 'Binnaguri',
    'RRB': 'Birur',
    'BTTR': 'Bitragunta',
    'BRRG': 'Biyavara Rajgarh',
    'VBL': 'Bobbili',
    'BONA': 'Boinda',
    'BKSC': 'Bokaro Steel City',
    'BHP': 'Bolpur Shantiniketan',
    'BVI': 'Borivali',
    'BTD': 'Botad',
    'BEM': 'Budaun',
    'BUDI': 'Bundi',
    'BAU': 'Burhanpur',
    'BUW': 'Burhwal',
    'BXR': 'Buxar',
    'CNO': 'Canacona',
    'CAA': 'Chakia',
    'CHKB': 'Chakki Bank',
    'CKP': 'Chakradharpur',
    'CSN': 'Chalisgaon',
    'CPH': 'Champa',
    'CNA': 'Chanderiya',
    'CDG': 'Chandigarh',
    'CNI': 'Chandil',
    'CD': 'Chandrapur',
    'CRP': 'Chandrapura',
    'CPK': 'Chaparmukh',
    'CAP': 'Chatrapur',
    'CGL': 'Chengalpattu Junction',
    'CNGR': 'Chengannur',
    'MAS': 'Chennai Central',
    'MS': 'Chennai Egmore',
    'CPR': 'Chhapra',
    'CWA': 'Chhindwara',
    'CDM': 'Chidambaram',
    'JRU': 'Chikjajur',
    'CHI': 'Chiplun',
    'CLX': 'Chirala',
    'CKTD': 'Chitrakootdham Karvi',
    'CRJ': 'Chittaranjan',
    'COR': 'Chittaurgarh',
    'CTO': 'Chittoor',
    'CPU': 'Chopan',
    'CAR': 'Chunar',
    'CUR': 'Churu',
    'CBE': 'Coimbatore Junction',
    'ONR': 'Coonoor',
    'CUPJ': 'Cuddalore Port',
    'HX': 'Cuddapah',
    'CTC': 'Cuttack',
    'DR': 'Dadar',
    'DRD': 'Dahanu Road',
    'DHD': 'Dahod',
    'DLO': 'Dalgaon',
    'DTO': 'Daltonganj',
    'DRZ': 'Dallirajhara',
    'DMO': 'Damoh',
    'DNR': 'Danapur',
    'DBG': 'Darbhanga',
    'DD': 'Daund',
    'DVG': 'Davangere',
    'DDN': 'Dehradun',
    'DOS': 'Dehri On Sone',
    'DLI': 'Delhi',
    'NDLS': 'New Delhi',
    'DEC': 'Delhi Cantt.',
    'DEE': 'Delhi Sarai Rohilla',
    'DSA': 'Delhi Shahdara',
    'DEOS': 'Deoria Sadar',
    'DVL': 'Devlali',
    'DMN': 'Dhamangaon',
    'DHN': 'Dhanbad',
    'DAB': 'Dharmabad',
    'DMR': 'Dharmanagar',
    'DPJ': 'Dharmapuri',
    'DMM': 'Dharmavaram',
    'DWR': 'Dharwad',
    'DAS': 'Dhasa',
    'DHO': 'Dhaulpur',
    'DNUL': 'Dhenuanal',
    'DLJ': 'Dhola',
    'DHNE': 'Dhone',
    'DHG': 'Dhrangadhra',
    'DBB': 'Dhubri',
    'DUI': 'Dhuri',
    'DBRG': 'Dibrugarh',
    'DBRT': 'Dibrugarh Town',
    'DGHA': 'Digha',
    'DLN': 'Dildarnagar',
    'DMV': 'Dimapur',
    'DG': 'Dindigul Junction',
    'DGG': 'Dongargarh',
    'DKJ': 'Dornakal',
    'DNRP': 'Dungarpur',
    'DURG': 'Durg',
    'DGR': 'Durgapur',
    'DVD': 'Duvvada',
    'DWK': 'Dwarka',
    'EE': 'Eluru',
    'ERS': 'Ernakulam Junction',
    'ERN': 'Ernakulam Town',
    'ED': 'Erode',
    'ETW': 'Etawah',
    'FD': 'Faizabad',
    'FDB': 'Faridabad',
    'FBD': 'Farrukhabad',
    'FTD': 'Fatehabad Chand',
    'FTP': 'Fatehpur',
    'FUT': 'Fatuha',
    'FKA': 'Fazilka',
    'FZD': 'Firozabad',
    'FZP': 'Firozpur City',
    'FZR': 'Firozpur Cantt.',
    'FBG': 'Forbesganj',
    'FKG': 'Furkating',
    'GDG': 'Gadag',
    'GJL': 'Gajraula',
    'GIM': 'Gandhidham',
    'GADJ': 'Gandhinagar',
    'GGC': 'Gangapur City',
    'GHD': 'Garwa Road',
    'GAYA': 'Gaya',
    'GAD': 'Gevra Road',
    'GTS': 'Ghatsila',
    'GZB': 'Ghaziabad',
    'GLPT': 'Goalpara Town',
    'GDA': 'Godhra',
    'GK': 'Gola Gokarannath',
    'GD': 'Gonda',
    'G': 'Gondia',
    'GY': 'Gooty',
    'GKP': 'Gorakhpur',
    'GOGH': 'Gossaingaon Hat',
    'GDV': 'Gudivada',
    'GDR': 'Gudur',
    'GR': 'Gulbarga',
    'GUNA': 'Guna',
    'GTL': 'Guntakal',
    'GNT': 'Guntur',
    'GGN': 'Gurgaon',
    'GUV': 'Guruvayur',
    'GHY': 'Guwahati',
    'GWL': 'Gwalior',
    'GYN': 'Gyanpur Road',
    'HBJ': 'Habibganj',
    'HJP': 'Hajipur',
    'HLZ': 'Haldia',
    'HDB': 'Haldibari',
    'HOJ': 'HamitonganJ',
    'HMH': 'Hanumangarh',
    'HAPA': 'Hapa',
    'HPU': 'Hapur',
    'HD': 'Harda',
    'HW': 'Haridwar',
    'HRR': 'Harihar',
    'HPP': 'Harpalpur',
    'HSA': 'Hasimara',
    'HTE': 'Hatia',
    'NED': 'Hazur Sahib Nanded',
    'HIL': 'Hilsa',
    'HMT': 'Himmat Nagar',
    'HUP': 'Hindupur',
    'HNL': 'Hingoli',
    'HSR': 'Hisar',
    'HBD': 'Hoshangabad',
    'HPT': 'Hospet',
    'HSRA': 'Hosur',
    'HBG': 'HowbadH',
    'HWH': 'Howrah',
    'UBL': 'Hubli',
    'HYB': 'Hyderabad',
    'IGP': 'Igatpuri',
    'IAA': 'Indara',
    'INDB': 'Indore',
    'IPR': 'Islampur',
    'ET': 'Itarsi',
    'JBP': 'Jabalpur',
    'JDB': 'Jagdalpur',
    'JP': 'Jaipur',
    'JYP': 'Jaypur',
    'JSM': 'Jaisalmer',
    'JJKR': 'Jajpur Keonjhar Road',
    'JHL': 'Jakhal',
    'JM': 'Jalamb',
    'JRC': 'Jalandhar Cantt.',
    'JUC': 'Jalandhar City',
    'JL': 'Jalgaon',
    'J': 'Jalna',
    'JPG': 'Jalpaiguri',
    'JMP': 'Jamalpur',
    'JAT': 'Jammu Tawi',
    'JAM': 'Jamnagar',
    'JNH': 'Janghai',
    'JSME': 'Jasidih',
    'JNU': 'Jaunpur Junction',
    'JYG': 'Jaynagar',
    'JLR': 'Jetalsar',
    'JAJ': 'Jhajha',
    'JHS': 'Jhansi',
    'JGM': 'Jhargram',
    'JSG': 'Jharsuguda',
    'JIND': 'Jind',
    'JU': 'Jodhpur',
    'JBN': 'Jogbani',
    'JTJ': 'Jolarpettai',
    'JT': 'Jorhat',
    'JND': 'Junagadh Junction',
    'KCG': 'Kacheguda',
    'COA': 'Kakinada Port',
    'KCF': 'Kalchini',
    'KLK': 'Kalka',
    'KLL': 'Kalol',
    'KYN': 'Kalyan',
    'KYQ': 'Kamakhya',
    'CJ': 'Kanchipuram',
    'KQL': 'Kandhla',
    'CAPE': 'Kanniyakumari',
    'CAN': 'Kannur',
    'CNB': 'Kanpur Central',
    'CPA': 'Kanpur Anwarganj',
    'CPJ': 'Kaptanganj',
    'KIK': 'Karaikal',
    'KKDI': 'Karaikkudi Junction',
    'KXJ': 'Karimganj',
    'KUN': 'Karnal',
    'KRR': 'Karur',
    'KAWR': 'Karwar',
    'KGQ': 'Kasaragod',
    'KSJ': 'Kasganj',
    'KGM': 'Kathgodam',
    'KIR': 'Katihar',
    'KTE': 'Katni',
    'KMZ': 'Katni Murwara',
    'KPD': 'Katpadi',
    'KWAE': 'Katwa',
    'KZJ': 'Kazipet',
    'KSNG': 'Kesinga',
    'KDJR': 'Kendujhargarh',
    'KGG': 'Khagaria',
    'KLD': 'Khalilabad',
    'KMT': 'Khammam',
    'KNW': 'Khandwa',
    'KGP': 'Kharagpur',
    'KEX': 'Khekra',
    'KUR': 'Khurda Road',
    'KRJ': 'Khurja',
    'KNE': 'Kishanganj',
    'KSG': 'Kishangarh',
    'KIUL': 'Kiul',
    'KCVL': 'Kochuveli',
    'KQN': 'Kodaikanal Road',
    'KOAA': 'Kolkata',
    'QLN': 'Kollam',
    'KPG': 'Kopargaon',
    'KRPU': 'Koraput',
    'KRBA': 'Korba',
    'KOTA': 'Kota',
    'KTW': 'Kotdwara',
    'KKP': 'Kot Kapura',
    'KTYM': 'Kottayam',
    'CLT': 'Kozhikode',
    'KNJ': 'Krishnanagar City',
    'KJM': 'Krishnarajapuram',
    'KUGT': 'Kumarghat',
    'KMU': 'Kumbakonam',
    'KUDA': 'Kundapura',
    'KWV': 'Kurduwadi',
    'KRNT': 'Kurnool Town',
    'KKDE': 'Kurukshetra',
    'LMP': 'Lakhimpur',
    'LRJ': 'Laksar',
    'LGH': 'Lalgarh',
    'LGL': 'Lalgola',
    'LAR': 'Lalitpur',
    'LKU': 'Lalkuan Junction',
    'LUR': 'Latur',
    'LEDO': 'Ledo',
    'LHU': 'Loharu',
    'LTT': 'Lokmanya Tilak Terminus',
    'LNL': 'Lonavla',
    'LD': 'Londa',
    'LFG': 'Lower Haflong',
    'LJN': 'Lucknow',
    'LKO': 'Lucknow',
    'LDH': 'Ludhiana',
    'LMG': 'Lumding',
    'LUNI': 'Luni',
    'MTM': 'Machilipatnam',
    'MDT': 'Madarihat',
    'MAD': 'Maddur',
    'MAO': 'Madgaon',
    'MBI': 'Madhubani',
    'MDP': 'Madhupur',
    'MDU': 'Madurai Junction',
    'MSMD': 'Mahasamund',
    'MBNR': 'Mahbubnagar',
    'MHV': 'Mahuva',
    'MNGD': 'Muniguda',
    'MSH': 'Mahesana',
    'MBA': 'Mahoba',
    'MLN': 'Mailani',
    'MKC': 'Maksi',
    'MLDT': 'Malda Town',
    'MNM': 'Manamadurai',
    'MUV': 'Manduadih',
    'MAQ': 'Mangalore Central',
    'MAJN': 'Mangalore Junction',
    'MKP': 'Manikpur',
    'MUR': 'Mankapur',
    'MMR': 'Manmad',
    'MQ': 'Mannargudi',
    'MNE': 'Mansi',
    'MANU': 'Manu',
    'MXN': 'Mariani',
    'MJ': 'Marwar Junction',
    'MTJ': 'Mathura',
    'MAU': 'Mau',
    'MV': 'Mayiladuturai Junction',
    'MTC': 'Meerut City',
    'MTD': 'Merta Road',
    'MTP': 'Mettupalayam',
    'MDN': 'Midnapore',
    'MRJ': 'Miraj',
    'MRGA': 'Miryalaguda',
    'MZP': 'Mirzapur',
    'MOF': 'Moga',
    'MKA': 'Mokama',
    'MB': 'Moradabad',
    'MKI': 'Motihari',
    'MUE': 'Mudkhed',
    'MGS': 'Mughalsarai',
    'BCT': 'Mumbai Central',
    'CSTM': 'Mumbai CST',
    'MURI': 'Muri',
    'MZS': 'Murkeongselek',
    'MZR': 'Murtajapur',
    'MOZ': 'Muzaffarnagar',
    'MFP': 'Muzaffarpur',
    'MYS': 'Mysore',
    'NDAE': 'Nabadwip Dham',
    'ND': 'Nadiad',
    'NDKD': 'Nadikudi',
    'NGT': 'Nagappattinam',
    'NKB': 'Nagarkata',
    'NSL': 'Nagarsol',
    'NAB': 'Nagbhir',
    'NAD': 'Nagda',
    'NCJ': 'Nagercoil Junction',
    'NCR': 'Nagore',
    'NGP': 'Nagpur',
    'NIR': 'Nainpur',
    'NBD': 'Najibabad',
    'NLD': 'Nalanda',
    'NLDA': 'Nalgonda',
    'NMKL': 'Namakkal',
    'NRE': 'Nandalur',
    'NGN': 'Nandgaon',
    'NDB': 'Nandurbar',
    'NDL': 'Nandyal',
    'NLDM': 'Nangal Dam',
    'NKE': 'Narkatiaganj',
    'NS': 'Narasapur',
    'NU': 'Narsingpur',
    'NRW': 'Narwana',
    'NK': 'Nasik Road',
    'NUH': 'Naugarh',
    'NLR': 'Nellore',
    'GMO': 'Netaji Subhash Chandra Bose Gomoh',
    'NOQ': 'New Alipurduar',
    'NBQ': 'New Bongaigaon',
    'NCB': 'New Cooch Behar',
    'NFK': 'New Farakka',
    'NJP': 'New Jalpaiguri',
    'NMZ': 'New Mal Junction',
    'NTSK': 'New Tinsukia',
    'NDD': 'Nidadavolu',
    'NMJ': 'Nidamangalam',
    'NDO': 'Nidubrolu',
    'NMH': 'Nimach',
    'NZB': 'Nizamabad',
    'NZM': 'Nizamuddin',
    'NOLI': 'Noli',
    'NLP': 'North Lakhimpur',
    'ODB': 'Odlabari',
    'OKHA': 'Okha',
    'OGL': 'Ongole',
    'ORAI': 'Orai',
    'PC': 'Pachora',
    'PLNI': 'Palani',
    'PNU': 'Palanpur',
    'PSA': 'Palasa',
    'PGT': 'Palakkad',
    'PGTN': 'Palakkad Town',
    'PLK': 'Paliakalan',
    'PVR': 'Pandharapur',
    'PNP': 'Panipat',
    'PRDP': 'Paradeep',
    'PNME': 'Parasnath',
    'PNVL': 'Panvel',
    'PBN': 'Parbhani',
    'PVPT': 'Parvatipuram Town',
    'PTK': 'Pathankot',
    'PTA': 'Patiala',
    'PNBE': 'Patna',
    'PNC': 'Patna Sahib',
    'PLC': 'Phalodi',
    'PFM': 'Phaphamau',
    'FL': 'Phulera',
    'PBE': 'Pilibhit',
    'PPI': 'Pipariya',
    'PTJ': 'Podanur',
    'PBR': 'Porbandar',
    'PBH': 'Pratapgarh',
    'PDY': 'Puducherry',
    'SCL': 'Silchar',
    'SHTT': 'Silghat',
    'SGUJ': 'Siliguri',
    'SGUT': 'Siliguri Town',
    'SLGR': 'Simaluguri',
    'SGRL': 'Singrauli',
    'SKZR': 'Sirpur Kagaznagar',
    'SSA': 'Sirsa',
    'SBZ': 'Siswa Bazar',
    'SMI': 'Sitamarhi',
    'SPC': 'Sitapur City',
    'SCC': 'Sitapur Cantt.',
    'SURI': 'Siuri',
    'SV': 'Siwan',
    'SOD': 'Sojat Road',
    'SOL': 'Solan',
    'SUR': 'Solapur',
    'SMNH': 'Somnath',
    'SPT': 'Sompeta',
    'SEE': 'Sonpur',
    'CSMT': 'Chhatrapati Shivaji Maharaj Terminus',
    'SDGH': 'Sri Dungargarh',
    'SGNR': 'Sri Ganganagar',
    'SA': 'Salem Junction',
    'CHE': 'Srikakulam Road',
    'SSPN': 'Sri Sathya Sai Prashanti Nilayam',
    'SUJH': 'Sujangarh',
    'SLN': 'Sultanpur',
    'ST': 'Surat',
    'SOG': 'Suratgarh',
    'SL': 'Surathkal',
    'SUNR': 'Surendranagar',
    'TDD': 'Tadepalligudem',
    'TBM': 'Tambaram',
    'TATA': 'Tatanagar',
    'TLY': 'Thalassery',
    'TEL': 'Tenali',
    'TS': 'Tenkasi',
    'TZTB': 'Tezpur',
    'TJ': 'Thanjavur',
    'TVR': 'Thiruvarur',
    'TPJ': 'Tiruchchirappalli Junction',
    'TCN': 'Tiruchendur',
    'TEN': 'Tirunelveli',
    'TPTY': 'Tirupati',
    'TUP': 'Tiruppur',
    'TIR': 'Tirur',
    'TIG': 'Titlagarh',
    'TCR': 'Thrissur',
    'TVC': 'Thiruvananthapuram',
    'TNM': 'Tiruvannamalai',
    'TMR': 'Tumsar Road',
    'TDL': 'Tundla',
    'TUNI': 'Tuni',
    'TN': 'Tuticorin',
    'TRL': 'Tiruvallur',
    'UDZ': 'Udaipur City',
    'UHP': 'Udhampur',
    'UDN': 'Udhna',
    'UD': 'Udupi',
    'UJN': 'Ujjain',
    'UNA': 'Una',
    'UCR': 'Unchahar',
    'ON': 'Unnao',
    'BDJ': 'Vadakara',
    'BRC': 'Vadodara',
    'BL': 'Valsad',
    'MEJ': 'Vanchi Maniyachchi Junction',
    'BSB': 'Varanasi',
    'VAK': 'Varkala',
    'BSR': 'Vasai Road',
    'VSG': 'Vasco Da Gama',
    'VLKN': 'Velankanni',
    'VRL': 'Veraval',
    'BHS': 'Vidisha',
    'BZA': 'Vijayawada',
    'VM': 'Villupuram Junction',
    'VG': 'Viramgam',
    'VPT': 'Virudunagar Junction',
    'VSKP': 'Visakhapatnam',
    'VZM': 'Vizianagaram',
    'VRI': 'Vriddhachalam Junction',
    'WADI': 'Wadi',
    'WKR': 'Wankaner',
    'WL': 'Warangal',
    'WR': 'Wardha Junction',
    'YPR': 'Yesvantpur',
    'ZBD': 'Zafarabad',
  };

  /// method [getName] will return the station name if it is
  /// available in the map [_stations] else, it is good to use the
  /// station code which is passed to this method.
  static String getName(String stationCode) {
    return _stations[stationCode.toUpperCase().trim()] ?? stationCode;
  }

  /// method [exists] is un-used for now, later it will be used
  /// so ignore for review
  static bool exists(String? stationCode) {
    if (stationCode == null) return false;
    return _stations.containsKey(stationCode.toUpperCase().trim());
  }
}
