default_platform(:android)

platform :android do

  desc "Build Flutter AAB & upload to Play Store Internal Testing"
  lane :internal do
    flutter_prepare
    flutter_build_aab
    upload(track: "internal")
  end

  desc "Build Flutter AAB & upload to Play Store Closed Testing"
  lane :beta do
    flutter_prepare
    flutter_build_aab
    upload(track: "closed")
  end

  desc "Build Flutter AAB & upload to Play Store Production"
  lane :production do
    flutter_prepare
    flutter_build_aab
    upload(track: "production")
  end

  # -------------------------------
  # Shared methods
  # -------------------------------

  private_lane :flutter_prepare do
    sh "fvm flutter clean"
    sh "fvm flutter pub get"
  end

  private_lane :flutter_build_aab do
    sh "fvm flutter build appbundle --release"
  end

  private_lane :upload do |options|
    upload_to_play_store(
      track: options[:track],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end
